# This file needs to be modified and placed in 'resources/' in the directory above this one.
# Keys
title = "My TOML Config"

# Tables
[sms]
origin = "YOUR_SERVICE"
carrier = "TW"

[db]
sqlite_path = "your_database.db"

[server]
  [server.dev]
  PORT = 8888  # will be lower cased when reading.
  base_url = "https://localhost:8888/"
  [server.prod]
  port = 443
  base_url = "https://www.yourwebsite.com/"

[scheduler]
  [scheduler.prod]
  max_retries = 1
  reminder_delay = 1800  # 30 minutes in seconds
  ping = ['9:30', '17:30']
  [scheduler.dev]
  max_retries = 3
  reminder_delay = 45
  ping = ['12:30', '17:30', '14:12']
