# Keys
title = "My TOML Config"
# Tables
[sms]
origin = "COVIDUCI"
carrier = "TW"
[db]
sqlite_path = "/home/psc/resources/coviduci.db"
[server]
  [server.dev]
  PORT = 8888  # will be lower cased when reading.
  base_url = "https://localhost:8888/"
  [server.prod]
  port = 443
  base_url = "https://www.coviduci.com/"
[scheduler]
  [scheduler.dev]
  max_retries = 3
  reminder_delay = 45
  ping = ['9:30', '17:00'] # UTC time
  [scheduler.prod]
  max_retries = 1
  reminder_delay = 1800  # 30 minutes in seconds
  ping = ['8:30', '16:00'] # UTC time
