# Keys
title = "My TOML Config"

# Tables
[sms]
origin = "COVIDUCI"
carrier = "nx"

[db]
sqlite_path = "test.db"

[server]
  [server.dev]
  PORT = 8888  # will be lower cased when reading.
  base_url = "https://localhost"
  [server.prod]
  port = 443
  base_url = "https://www.coviduci.net/"

[scheduler]
  [scheduler.prod]
  max_retries = 3
  [scheduler.dev]
  max_retries = 1
